"""add_admin_features_blocking_and_cot_codes

Revision ID: 28509d21ba1d
Revises: update_notifications
Create Date: 2026-05-24 11:02:44.447028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28509d21ba1d'
down_revision = 'update_notifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('blocked_reason', sa.Text(), nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('transaction', 'security', 'system', 'admin', name='notificationtype'),
               nullable=True,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('unread', 'read', name='notificationstatus'),
               nullable=True,
               existing_server_default=sa.text("'unread'::notificationstatus"))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.add_column('users', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('blocked_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_reason')
    op.drop_column('users', 'blocked_at')
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('unread', 'read', name='notificationstatus'),
               nullable=False,
               existing_server_default=sa.text("'unread'::notificationstatus"))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('transaction', 'security', 'system', 'admin', name='notificationtype'),
               nullable=False,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.drop_column('accounts', 'blocked_reason')
    op.drop_column('accounts', 'blocked_at')
    # ### end Alembic commands ###
