"""Add PIN security fields

Revision ID: d165c639ab42
Revises: 28509d21ba1d
Create Date: 2026-05-24 12:10:03.779550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd165c639ab42'
down_revision = '28509d21ba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_failed_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pin_locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_locked_until')
    op.drop_column('users', 'pin_failed_attempts')
    # ### end Alembic commands ###
